[versions]
activityCompose = "1.10.1"
activityKtx = "1.9.1"
analyticsConnector = "1.0.0"
androidGradlePlugin = "8.10.1"
androidJunit5 = "1.12.2.0"
appcompat = "1.4.1"
composeBom = "2025.06.01"
composeUi = "1.6.8"
constraintlayout = "2.1.3"
coreKtx = "1.7.0"
coroutines = "1.8.1"
dokka = "2.0.0"
espressoCore = "3.4.0"
experimentAndroidClient = "1.6.3"
fragmentKtx = "1.8.2"
gson = "2.10"
json = "20211205"
junit = "5.9.3"
junit4 = "4.13.2"
kotlin = "1.9.25"
kotlinCompilerExtension = "1.5.15"
ktlint = "12.3.0"
material = "1.5.0"
mavenPublish = "0.33.0"
mockk = "1.13.13"
mockwebserver = "4.10.0"
okhttp = "4.12.0"
playServicesAdsIdentifier = "18.0.1"
playServicesAppset = "16.0.2"
playServicesBase = "18.0.1"
robolectric = "4.15.1"
testCore = "1.4.0"
testExtJunit = "1.1.3"
testRunner = "1.4.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
analytics-connector = { module = "com.amplitude:analytics-connector", version.ref = "analyticsConnector" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" } # Added
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "composeUi" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" } # Added
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
experiment-android-client = { module = "com.amplitude:experiment-android-client", version.ref = "experimentAndroidClient" } # Added
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" } # Added
json = { module = "org.json:json", version.ref = "json" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params" }
junit-vintage-engine = { module = "org.junit.vintage:junit-vintage-engine" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
material = { module = "com.google.android.material:material", version.ref = "material" } # Added
material3 = { module = "androidx.compose.material3:material3" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
playServicesAdsIdentifier = { module = "com.google.android.gms:play-services-ads-identifier", version.ref = "playServicesAdsIdentifier" }
playServicesAppset = { module = "com.google.android.gms:play-services-appset", version.ref = "playServicesAppset" }
play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
test-core = { module = "androidx.test:core", version.ref = "testCore" }
test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "testExtJunit" }
test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
ui = { module = "androidx.compose.ui:ui" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "androidJunit5" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
android-test = { id = "com.android.test", version.ref = "androidGradlePlugin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
